version: '3.8'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: ros:kinetic-ros-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  buddy:
    build: 
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - ros-master
    environment:
      - USER
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=buddy"
      - "LIBGL_ALWAYS_INDIRECT=0"
      - "DISPLAY=host.docker.internal:0.0"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    networks:
      - ros
    restart: always
    volumes:
      - ../buddy/src/motor_control_drivers:/home/buddy/ros/src/motor_control_drivers
      - ../buddy/src/sensor_to_laser:/home/buddy/ros/src/sensor_to_laser
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      #- /home/$USER:/home/$USER:rw #share your home with write permissions


  #viz:
  #  image: osrf/ros:kinetic-desktop-full
  #  container_name: ros_visualizer
  #  depends_on:
  #    - ros-master
  #  networks:
  #    - ros
  #  environment:
  #    - USER
  #    - "ROS_MASTER_URI=http://ros-master:11311"
  #    - "ROS_HOSTNAME=ros_visualizer"
  #    - "LIBGL_ALWAYS_INDIRECT=0"
  #    - "DISPLAY=host.docker.internal:0.0"
  #    - "QT_X11_NO_MITSHM=1" #fix some QT bugs
  #  #share your user to the container in order to access your x11
  #  user: 1000:1000 #adapt as needed!
  #  volumes:
  #    #share your x11 socket and permissions to the container
  #    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #    - /etc/group:/etc/group:ro
  #    - /etc/passwd:/etc/passwd:ro
  #    - /etc/shadow:/etc/shadow:ro
  #    - /etc/sudoers.d:/etc/sudoers.d:ro
  #    - /home/$USER:/home/$USER:rw #share your home with write permissions
  #  command: rviz
  #  restart: always