version: '3.8'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: ros:kinetic-ros-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  buddy:
    build: 
      context: ..
      dockerfile: Dockerfile
      args:
        - USER=$USER
    depends_on:
      - ros-master
    environment:
      - USER
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=buddy"
      - "LIBGL_ALWAYS_INDIRECT=0"
      #- "DISPLAY"   #LINUX
      - "DISPLAY=host.docker.internal:0.0"   #WINDOWS
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    networks:
      - ros
    restart: always
    volumes:
      - ../buddy/src/motor_control_drivers:/home/$USER/ros/src/motor_control_drivers
      - ../buddy/src/sensor_to_laser:/home/$USER/ros/src/sensor_to_laser
      - ../buddy/src/buddy_launch.launch:/home/$USER/ros/src/buddy_launch.launch
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
    command: ["sleep", "10000"]
